### ISSUE TITLE
Invalid path error when cloning repository

### ISSUE THREAD

**Issue by f8dca** [carlota/showmethemoney#3]
Hello,

I recommend renaming the file 'F*** Security Maturity! Let's Talk about Security Health.pdf' because git does not like it.

`
remote: Enumerating objects: 112, done.  
remote: Counting objects: 100% (28/28), done.  
remote: Compressing objects: 100% (26/26), done.  
remote: Total 112 (delta 11), reused 8 (delta 1), pack-reused 84  
Receiving objects: 100% (112/112), 9.55 MiB | 5.01 MiB/s, done.  
Resolving deltas: 100% (45/45), done.  
error: invalid path 'F*** Security Maturity! Let's Talk about Security Health.pdf'  
fatal: unable to checkout working tree  
warning: Clone succeeded, but checkout failed.  
You can inspect what was checked out with 'git status'  
and retry with 'git restore --source=HEAD :/'  
`

**Comment by carlota** [comment]
Fixed!
